config/routes.rb
Rails.application.routes.draw do
resources:sessions, only: [:new,:create,:destroy]
get'signup',to:  'users#new', as: 'signup'
get'login',to: 'sessions#new',  as: 'login'
get'logout',to: 'sessions#destroy', as: 'logout'

  get 'page/index'
  root'page#index'

  resources :articles do
   resources :comments do
    resources :users
    
   end
  end
 

end

app/models/article.rb
class Article < ActiveRecord::Base
has_many :comments , dependent: :destroy
belongs_to :user
validates :title, presence: true,
                    length: { minimum: 5 }


end

app/models/comment.rb
class Comment < ActiveRecord::Base
 belongs_to :article, polymorphic: true
 belongs_to :user
 validates_presence_of :users
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :articles
has_many :comments
  has_secure_password
  validates            :first_name, presence:            true
validates            :last_name, presence:            true
validates            :email, presence:            true,
uniqueness:            true, 
format:            {
with:            /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
}
   def to_s
"#{first_name} #{last_name}"
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
private
def current_user
User.where(id: session[:user_id]).first
end
helper_method :current_user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
def index
    @articles = Article.all
  end

def show
    @article = Article.find(params[:id])
  end
def new
@article = Article.new
end
def edit
  @article = Article.find(params[:id])
end
def create
  @article = Article.new(article_params)
 if @article.save
    redirect_to @article
  else
    render 'new'
  end
end
def update
  @article = Article.find(params[:id])
 
  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end
def destroy
  @article = Article.find(params[:id])
  @article.destroy
 
  redirect_to articles_path
end 
private
  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_filter :authenticate, :only => [:create, :destroy]

def create
    @article = Article.find(params[:article_id])
    @comments=@article.comments
    @comment=current_user.comments.build(params[:comment])
     @comment.article=Comment.new
   if @comment.save
      flash[:notice] = "Comment was saved"
    else
      flash[:error] = "There was an error saving the comment. Please try again."
    end 
   
    respond_to do |format|
    
    format.html
    format.js
      end
 end
 
 def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
    
    respond_to do |format|
    format.html { redirect_to article_path(@article) }
    format.js
  end
  
  def show
  @comment=Comment.new
  @comment=current_user
  end
  
  def index
  @comments = Comment.all
  end
 
  private
    def comment_params
      params.require(:comment).permit(:body)
                               
    end
end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

   def create
  user = User.find_by_email(params[:email])
if user && user.authenticate(params[:password])
session[:user_id]  = user.id
redirect_to  root_url,notice:'Logged in!'
 else
render:new
    end
 end

  def destroy
session[:user_id] =  nil
redirect_to root_url,notice:'Logged out!'
end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
     session[:user_id] = @user.id
      redirect_to root_url, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>
 <table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 <p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<p>
<%= link_to "Comments", "#", id: "comments-link" %>
</p>
<section id="comments-section">
<ol id="comments">
<%= render @article.comments %>
</ol>
<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build], remote: true) do |f| %>
<p>
 <b> <%= current_user %> </b> <br>
<%= f.label "your comment" %> <br>
<%= f.text_area :body %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>
</section>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<span>Posted <%= time_ago_in_words(comment.created_at) %> ago </span>
<p>
<strong>Comment:</strong><br>
<b><%= current_user %></b> <br>
  <%= comment.body %> 
</p>

<%= link_to 'Destroy',@comments,
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build], remote: true) do |f| %> 
<p>
<%= current_user %><br>
</p>
 <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/create.js.erb
$('#comments').append("<%= j render @comment %>");
$('#comment_body').val("");
$('#comment_current_user').val("");

app/views/comments/index.html.erb
<h> listing comments </h>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div id="user_header">
<% if current_user  %>
 Logged in  as  <%= current_user.email %>.
  <%=link_to"Log Out",logout_path %>
<% else %>
  <%= link_to "Sign Up", signup_path %> or
  <%= link_to "Log  In", login_path  %>
<%end %>
</div>
<% flash.each do |key, value| %>
<%= content_tag(:div, class: "alert alert-#key") do %>
<p><%=  value %></p>
<%end %>
<%end %>

<%= yield %>

</body>
</html>

app/views/page/index.html.erb
<h1><strong> Welcome to Blog Application </strong> </h1>
<%= link_to 'My Blog', controller: 'articles' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Hello , Rails !</h1>
<%= link_to 'My Blog', controller: 'articles' %>